version: '3'
services:
  frontend:
    image: chess_project/frontend
    restart: always
    volumes:
      - ./chess_frontend:/workspace/chess_frontend:cached
      - ./shared:/workspace/shared:cached
    build: 
      dockerfile: ./chess_frontend/dev.dockerfile
    command: sleep infinity
  backend:
    image: chess_project/backend
    restart: always
    volumes:
      - ./chess_backend:/workspace/chess_backend:cached
      - ./shared:/workspace/shared:cached
    build:
      dockerfile: ./chess_backend/dev.dockerfile
    command: sleep infinity

    