// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: game_room_service/game_room_service.proto

package game_room_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UPDATE_TYPE int32

const (
	UPDATE_TYPE_IN_MATCHMAKING     UPDATE_TYPE = 0
	UPDATE_TYPE_ROOM_JOINED        UPDATE_TYPE = 1
	UPDATE_TYPE_GAME_STATE_UPDATED UPDATE_TYPE = 2
)

// Enum value maps for UPDATE_TYPE.
var (
	UPDATE_TYPE_name = map[int32]string{
		0: "IN_MATCHMAKING",
		1: "ROOM_JOINED",
		2: "GAME_STATE_UPDATED",
	}
	UPDATE_TYPE_value = map[string]int32{
		"IN_MATCHMAKING":     0,
		"ROOM_JOINED":        1,
		"GAME_STATE_UPDATED": 2,
	}
)

func (x UPDATE_TYPE) Enum() *UPDATE_TYPE {
	p := new(UPDATE_TYPE)
	*p = x
	return p
}

func (x UPDATE_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UPDATE_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_game_room_service_game_room_service_proto_enumTypes[0].Descriptor()
}

func (UPDATE_TYPE) Type() protoreflect.EnumType {
	return &file_game_room_service_game_room_service_proto_enumTypes[0]
}

func (x UPDATE_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UPDATE_TYPE.Descriptor instead.
func (UPDATE_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_game_room_service_game_room_service_proto_rawDescGZIP(), []int{0}
}

type PIECE int32

const (
	PIECE_PAWN   PIECE = 0
	PIECE_ROOK   PIECE = 1
	PIECE_KNIGHT PIECE = 2
	PIECE_BISHOP PIECE = 3
	PIECE_QUEEN  PIECE = 4
	PIECE_KING   PIECE = 5
)

// Enum value maps for PIECE.
var (
	PIECE_name = map[int32]string{
		0: "PAWN",
		1: "ROOK",
		2: "KNIGHT",
		3: "BISHOP",
		4: "QUEEN",
		5: "KING",
	}
	PIECE_value = map[string]int32{
		"PAWN":   0,
		"ROOK":   1,
		"KNIGHT": 2,
		"BISHOP": 3,
		"QUEEN":  4,
		"KING":   5,
	}
)

func (x PIECE) Enum() *PIECE {
	p := new(PIECE)
	*p = x
	return p
}

func (x PIECE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PIECE) Descriptor() protoreflect.EnumDescriptor {
	return file_game_room_service_game_room_service_proto_enumTypes[1].Descriptor()
}

func (PIECE) Type() protoreflect.EnumType {
	return &file_game_room_service_game_room_service_proto_enumTypes[1]
}

func (x PIECE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PIECE.Descriptor instead.
func (PIECE) EnumDescriptor() ([]byte, []int) {
	return file_game_room_service_game_room_service_proto_rawDescGZIP(), []int{1}
}

type GameState_GAME_STATE int32

const (
	GameState_NOT_STARTED GameState_GAME_STATE = 0
	GameState_ONGOING     GameState_GAME_STATE = 1
	GameState_FINISHED    GameState_GAME_STATE = 2
)

// Enum value maps for GameState_GAME_STATE.
var (
	GameState_GAME_STATE_name = map[int32]string{
		0: "NOT_STARTED",
		1: "ONGOING",
		2: "FINISHED",
	}
	GameState_GAME_STATE_value = map[string]int32{
		"NOT_STARTED": 0,
		"ONGOING":     1,
		"FINISHED":    2,
	}
)

func (x GameState_GAME_STATE) Enum() *GameState_GAME_STATE {
	p := new(GameState_GAME_STATE)
	*p = x
	return p
}

func (x GameState_GAME_STATE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameState_GAME_STATE) Descriptor() protoreflect.EnumDescriptor {
	return file_game_room_service_game_room_service_proto_enumTypes[2].Descriptor()
}

func (GameState_GAME_STATE) Type() protoreflect.EnumType {
	return &file_game_room_service_game_room_service_proto_enumTypes[2]
}

func (x GameState_GAME_STATE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameState_GAME_STATE.Descriptor instead.
func (GameState_GAME_STATE) EnumDescriptor() ([]byte, []int) {
	return file_game_room_service_game_room_service_proto_rawDescGZIP(), []int{2, 0}
}

type GameState_TURN int32

const (
	GameState_WHITE GameState_TURN = 0
	GameState_BLACK GameState_TURN = 1
)

// Enum value maps for GameState_TURN.
var (
	GameState_TURN_name = map[int32]string{
		0: "WHITE",
		1: "BLACK",
	}
	GameState_TURN_value = map[string]int32{
		"WHITE": 0,
		"BLACK": 1,
	}
)

func (x GameState_TURN) Enum() *GameState_TURN {
	p := new(GameState_TURN)
	*p = x
	return p
}

func (x GameState_TURN) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameState_TURN) Descriptor() protoreflect.EnumDescriptor {
	return file_game_room_service_game_room_service_proto_enumTypes[3].Descriptor()
}

func (GameState_TURN) Type() protoreflect.EnumType {
	return &file_game_room_service_game_room_service_proto_enumTypes[3]
}

func (x GameState_TURN) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameState_TURN.Descriptor instead.
func (GameState_TURN) EnumDescriptor() ([]byte, []int) {
	return file_game_room_service_game_room_service_proto_rawDescGZIP(), []int{2, 1}
}

type ConnectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName string `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_room_service_game_room_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_room_service_game_room_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_game_room_service_game_room_service_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type RoomUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UpdateType UPDATE_TYPE `protobuf:"varint,1,opt,name=updateType,proto3,enum=game_room_service.UPDATE_TYPE" json:"updateType,omitempty"`
	RoomId     *string     `protobuf:"bytes,2,opt,name=roomId,proto3,oneof" json:"roomId,omitempty"`
	GameState  *GameState  `protobuf:"bytes,3,opt,name=gameState,proto3,oneof" json:"gameState,omitempty"`
}

func (x *RoomUpdateResponse) Reset() {
	*x = RoomUpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_room_service_game_room_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomUpdateResponse) ProtoMessage() {}

func (x *RoomUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_room_service_game_room_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomUpdateResponse.ProtoReflect.Descriptor instead.
func (*RoomUpdateResponse) Descriptor() ([]byte, []int) {
	return file_game_room_service_game_room_service_proto_rawDescGZIP(), []int{1}
}

func (x *RoomUpdateResponse) GetUpdateType() UPDATE_TYPE {
	if x != nil {
		return x.UpdateType
	}
	return UPDATE_TYPE_IN_MATCHMAKING
}

func (x *RoomUpdateResponse) GetRoomId() string {
	if x != nil && x.RoomId != nil {
		return *x.RoomId
	}
	return ""
}

func (x *RoomUpdateResponse) GetGameState() *GameState {
	if x != nil {
		return x.GameState
	}
	return nil
}

type GameState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameState   GameState_GAME_STATE `protobuf:"varint,2,opt,name=gameState,proto3,enum=game_room_service.GameState_GAME_STATE" json:"gameState,omitempty"`
	CurrentTurn GameState_TURN       `protobuf:"varint,3,opt,name=currentTurn,proto3,enum=game_room_service.GameState_TURN" json:"currentTurn,omitempty"`
	ChessGame   *ChessGame           `protobuf:"bytes,4,opt,name=chessGame,proto3" json:"chessGame,omitempty"`
}

func (x *GameState) Reset() {
	*x = GameState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_room_service_game_room_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameState) ProtoMessage() {}

func (x *GameState) ProtoReflect() protoreflect.Message {
	mi := &file_game_room_service_game_room_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameState.ProtoReflect.Descriptor instead.
func (*GameState) Descriptor() ([]byte, []int) {
	return file_game_room_service_game_room_service_proto_rawDescGZIP(), []int{2}
}

func (x *GameState) GetGameState() GameState_GAME_STATE {
	if x != nil {
		return x.GameState
	}
	return GameState_NOT_STARTED
}

func (x *GameState) GetCurrentTurn() GameState_TURN {
	if x != nil {
		return x.CurrentTurn
	}
	return GameState_WHITE
}

func (x *GameState) GetChessGame() *ChessGame {
	if x != nil {
		return x.ChessGame
	}
	return nil
}

type ChessGame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	White string  `protobuf:"bytes,1,opt,name=white,proto3" json:"white,omitempty"`
	Black string  `protobuf:"bytes,2,opt,name=black,proto3" json:"black,omitempty"`
	Moves []*Move `protobuf:"bytes,3,rep,name=moves,proto3" json:"moves,omitempty"`
}

func (x *ChessGame) Reset() {
	*x = ChessGame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_room_service_game_room_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChessGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChessGame) ProtoMessage() {}

func (x *ChessGame) ProtoReflect() protoreflect.Message {
	mi := &file_game_room_service_game_room_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChessGame.ProtoReflect.Descriptor instead.
func (*ChessGame) Descriptor() ([]byte, []int) {
	return file_game_room_service_game_room_service_proto_rawDescGZIP(), []int{3}
}

func (x *ChessGame) GetWhite() string {
	if x != nil {
		return x.White
	}
	return ""
}

func (x *ChessGame) GetBlack() string {
	if x != nil {
		return x.Black
	}
	return ""
}

func (x *ChessGame) GetMoves() []*Move {
	if x != nil {
		return x.Moves
	}
	return nil
}

type Move struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Piece PIECE  `protobuf:"varint,1,opt,name=piece,proto3,enum=game_room_service.PIECE" json:"piece,omitempty"`
	From  string `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To    string `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
}

func (x *Move) Reset() {
	*x = Move{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_room_service_game_room_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Move) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Move) ProtoMessage() {}

func (x *Move) ProtoReflect() protoreflect.Message {
	mi := &file_game_room_service_game_room_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Move.ProtoReflect.Descriptor instead.
func (*Move) Descriptor() ([]byte, []int) {
	return file_game_room_service_game_room_service_proto_rawDescGZIP(), []int{4}
}

func (x *Move) GetPiece() PIECE {
	if x != nil {
		return x.Piece
	}
	return PIECE_PAWN
}

func (x *Move) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Move) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type MoveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId   string `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	UserName string `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	Move     *Move  `protobuf:"bytes,3,opt,name=move,proto3" json:"move,omitempty"`
}

func (x *MoveRequest) Reset() {
	*x = MoveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_room_service_game_room_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveRequest) ProtoMessage() {}

func (x *MoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_room_service_game_room_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveRequest.ProtoReflect.Descriptor instead.
func (*MoveRequest) Descriptor() ([]byte, []int) {
	return file_game_room_service_game_room_service_proto_rawDescGZIP(), []int{5}
}

func (x *MoveRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *MoveRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *MoveRequest) GetMove() *Move {
	if x != nil {
		return x.Move
	}
	return nil
}

type MoveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *MoveResponse) Reset() {
	*x = MoveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_room_service_game_room_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveResponse) ProtoMessage() {}

func (x *MoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_room_service_game_room_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveResponse.ProtoReflect.Descriptor instead.
func (*MoveResponse) Descriptor() ([]byte, []int) {
	return file_game_room_service_game_room_service_proto_rawDescGZIP(), []int{6}
}

func (x *MoveResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_game_room_service_game_room_service_proto protoreflect.FileDescriptor

var file_game_room_service_game_room_service_proto_rawDesc = []byte{
	0x0a, 0x29, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x67, 0x61, 0x6d,
	0x65, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x2c,
	0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0xcb, 0x01, 0x0a,
	0x12, 0x52, 0x6f, 0x6f, 0x6d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x72,
	0x6f, 0x6f, 0x6d, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x55, 0x50, 0x44, 0x41,
	0x54, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x88, 0x01, 0x01,
	0x12, 0x3f, 0x0a, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x48, 0x01, 0x52, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x88, 0x01,
	0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x42, 0x0c, 0x0a, 0x0a,
	0x5f, 0x67, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22, 0xab, 0x02, 0x0a, 0x09, 0x47,
	0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x45, 0x0a, 0x09, 0x67, 0x61, 0x6d, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x27, 0x2e, 0x67, 0x61,
	0x6d, 0x65, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x47, 0x41, 0x4d, 0x45, 0x5f, 0x53,
	0x54, 0x41, 0x54, 0x45, 0x52, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12,
	0x43, 0x0a, 0x0b, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x54, 0x75, 0x72, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x72, 0x6f, 0x6f, 0x6d,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x2e, 0x54, 0x55, 0x52, 0x4e, 0x52, 0x0b, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74,
	0x54, 0x75, 0x72, 0x6e, 0x12, 0x3a, 0x0a, 0x09, 0x63, 0x68, 0x65, 0x73, 0x73, 0x47, 0x61, 0x6d,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x72,
	0x6f, 0x6f, 0x6d, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x68, 0x65, 0x73,
	0x73, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x09, 0x63, 0x68, 0x65, 0x73, 0x73, 0x47, 0x61, 0x6d, 0x65,
	0x22, 0x38, 0x0a, 0x0a, 0x47, 0x41, 0x4d, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x12, 0x0f,
	0x0a, 0x0b, 0x4e, 0x4f, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x52, 0x54, 0x45, 0x44, 0x10, 0x00, 0x12,
	0x0b, 0x0a, 0x07, 0x4f, 0x4e, 0x47, 0x4f, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08,
	0x46, 0x49, 0x4e, 0x49, 0x53, 0x48, 0x45, 0x44, 0x10, 0x02, 0x22, 0x1c, 0x0a, 0x04, 0x54, 0x55,
	0x52, 0x4e, 0x12, 0x09, 0x0a, 0x05, 0x57, 0x48, 0x49, 0x54, 0x45, 0x10, 0x00, 0x12, 0x09, 0x0a,
	0x05, 0x42, 0x4c, 0x41, 0x43, 0x4b, 0x10, 0x01, 0x22, 0x66, 0x0a, 0x09, 0x43, 0x68, 0x65, 0x73,
	0x73, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x68, 0x69, 0x74, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x77, 0x68, 0x69, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x62,
	0x6c, 0x61, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x6c, 0x61, 0x63,
	0x6b, 0x12, 0x2d, 0x0a, 0x05, 0x6d, 0x6f, 0x76, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x05, 0x6d, 0x6f, 0x76, 0x65, 0x73,
	0x22, 0x5a, 0x0a, 0x04, 0x4d, 0x6f, 0x76, 0x65, 0x12, 0x2e, 0x0a, 0x05, 0x70, 0x69, 0x65, 0x63,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x72,
	0x6f, 0x6f, 0x6d, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x49, 0x45, 0x43,
	0x45, 0x52, 0x05, 0x70, 0x69, 0x65, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02,
	0x74, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x22, 0x6e, 0x0a, 0x0b,
	0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f,
	0x6d, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x2b, 0x0a, 0x04, 0x6d, 0x6f, 0x76, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x67, 0x61, 0x6d, 0x65, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x04, 0x6d, 0x6f, 0x76, 0x65, 0x22, 0x24, 0x0a, 0x0c,
	0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x2a, 0x4a, 0x0a, 0x0b, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x12, 0x12, 0x0a, 0x0e, 0x49, 0x4e, 0x5f, 0x4d, 0x41, 0x54, 0x43, 0x48, 0x4d, 0x41, 0x4b,
	0x49, 0x4e, 0x47, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x52, 0x4f, 0x4f, 0x4d, 0x5f, 0x4a, 0x4f,
	0x49, 0x4e, 0x45, 0x44, 0x10, 0x01, 0x12, 0x16, 0x0a, 0x12, 0x47, 0x41, 0x4d, 0x45, 0x5f, 0x53,
	0x54, 0x41, 0x54, 0x45, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x44, 0x10, 0x02, 0x2a, 0x48,
	0x0a, 0x05, 0x50, 0x49, 0x45, 0x43, 0x45, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x41, 0x57, 0x4e, 0x10,
	0x00, 0x12, 0x08, 0x0a, 0x04, 0x52, 0x4f, 0x4f, 0x4b, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x4b,
	0x4e, 0x49, 0x47, 0x48, 0x54, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x42, 0x49, 0x53, 0x48, 0x4f,
	0x50, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x51, 0x55, 0x45, 0x45, 0x4e, 0x10, 0x04, 0x12, 0x08,
	0x0a, 0x04, 0x4b, 0x49, 0x4e, 0x47, 0x10, 0x05, 0x32, 0xb5, 0x01, 0x0a, 0x0f, 0x47, 0x61, 0x6d,
	0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x55, 0x0a, 0x07,
	0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x21, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x72,
	0x6f, 0x6f, 0x6d, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x67, 0x61, 0x6d,
	0x65, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52,
	0x6f, 0x6f, 0x6d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x30, 0x01, 0x12, 0x4b, 0x0a, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x4d, 0x6f, 0x76, 0x65, 0x12,
	0x1e, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1f, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0xbd, 0x01, 0x0a, 0x15, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x72, 0x6f,
	0x6f, 0x6d, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x42, 0x14, 0x47, 0x61, 0x6d, 0x65,
	0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x50, 0x01, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62,
	0x75, 0x66, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x2f, 0x62, 0x75, 0x66, 0x2d, 0x74, 0x6f, 0x75, 0x72,
	0x2f, 0x67, 0x65, 0x6e, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0xa2, 0x02, 0x03, 0x47, 0x58, 0x58, 0xaa, 0x02, 0x0f, 0x47,
	0x61, 0x6d, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0xca, 0x02,
	0x0f, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0xe2, 0x02, 0x1b, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02,
	0x0f, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_game_room_service_game_room_service_proto_rawDescOnce sync.Once
	file_game_room_service_game_room_service_proto_rawDescData = file_game_room_service_game_room_service_proto_rawDesc
)

func file_game_room_service_game_room_service_proto_rawDescGZIP() []byte {
	file_game_room_service_game_room_service_proto_rawDescOnce.Do(func() {
		file_game_room_service_game_room_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_game_room_service_game_room_service_proto_rawDescData)
	})
	return file_game_room_service_game_room_service_proto_rawDescData
}

var file_game_room_service_game_room_service_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_game_room_service_game_room_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_game_room_service_game_room_service_proto_goTypes = []any{
	(UPDATE_TYPE)(0),           // 0: game_room_service.UPDATE_TYPE
	(PIECE)(0),                 // 1: game_room_service.PIECE
	(GameState_GAME_STATE)(0),  // 2: game_room_service.GameState.GAME_STATE
	(GameState_TURN)(0),        // 3: game_room_service.GameState.TURN
	(*ConnectRequest)(nil),     // 4: game_room_service.ConnectRequest
	(*RoomUpdateResponse)(nil), // 5: game_room_service.RoomUpdateResponse
	(*GameState)(nil),          // 6: game_room_service.GameState
	(*ChessGame)(nil),          // 7: game_room_service.ChessGame
	(*Move)(nil),               // 8: game_room_service.Move
	(*MoveRequest)(nil),        // 9: game_room_service.MoveRequest
	(*MoveResponse)(nil),       // 10: game_room_service.MoveResponse
}
var file_game_room_service_game_room_service_proto_depIdxs = []int32{
	0,  // 0: game_room_service.RoomUpdateResponse.updateType:type_name -> game_room_service.UPDATE_TYPE
	6,  // 1: game_room_service.RoomUpdateResponse.gameState:type_name -> game_room_service.GameState
	2,  // 2: game_room_service.GameState.gameState:type_name -> game_room_service.GameState.GAME_STATE
	3,  // 3: game_room_service.GameState.currentTurn:type_name -> game_room_service.GameState.TURN
	7,  // 4: game_room_service.GameState.chessGame:type_name -> game_room_service.ChessGame
	8,  // 5: game_room_service.ChessGame.moves:type_name -> game_room_service.Move
	1,  // 6: game_room_service.Move.piece:type_name -> game_room_service.PIECE
	8,  // 7: game_room_service.MoveRequest.move:type_name -> game_room_service.Move
	4,  // 8: game_room_service.GameRoomService.connect:input_type -> game_room_service.ConnectRequest
	9,  // 9: game_room_service.GameRoomService.sendMove:input_type -> game_room_service.MoveRequest
	5,  // 10: game_room_service.GameRoomService.connect:output_type -> game_room_service.RoomUpdateResponse
	10, // 11: game_room_service.GameRoomService.sendMove:output_type -> game_room_service.MoveResponse
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_game_room_service_game_room_service_proto_init() }
func file_game_room_service_game_room_service_proto_init() {
	if File_game_room_service_game_room_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_game_room_service_game_room_service_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ConnectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_room_service_game_room_service_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*RoomUpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_room_service_game_room_service_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GameState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_room_service_game_room_service_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ChessGame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_room_service_game_room_service_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*Move); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_room_service_game_room_service_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*MoveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_room_service_game_room_service_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*MoveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_game_room_service_game_room_service_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_game_room_service_game_room_service_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_game_room_service_game_room_service_proto_goTypes,
		DependencyIndexes: file_game_room_service_game_room_service_proto_depIdxs,
		EnumInfos:         file_game_room_service_game_room_service_proto_enumTypes,
		MessageInfos:      file_game_room_service_game_room_service_proto_msgTypes,
	}.Build()
	File_game_room_service_game_room_service_proto = out.File
	file_game_room_service_game_room_service_proto_rawDesc = nil
	file_game_room_service_game_room_service_proto_goTypes = nil
	file_game_room_service_game_room_service_proto_depIdxs = nil
}
